### ISSUE TITLE
Make Input Bigger

### ISSUE THREAD

**Issue by jaqque** [jaqque/midjourney-split#1]
**Is your feature request related to a problem? Please describe.**
uri input too sm0l

**Describe the solution you'd like**
beeger

**Describe alternatives you've considered**
not doing a thing

**Additional context**
submitted via Discord, translated by this submitter
https://discord.com/channels/753750469016551467/753750469553291291/1142484899840929863

**Comment by NimbleJinx** [comment]
I made the URI field bigger, was it not big enough?
