### ISSUE TITLE
Add submit button

### ISSUE THREAD

**Issue by jaqque** [jaqque/midjourney-split#2]
**Is your feature request related to a problem? Please describe.**
No submit button, have to hit return

**Describe the solution you'd like**
pls let me use mouse instead of keyboard

**Describe alternatives you've considered**
hitting return, like a pleb

**Additional context**
Submitted via Discord, translated by this submitter
https://discord.com/channels/753750469016551467/753750469553291291/1142484899840929863

**Comment by NimbleJinx** [comment]
So, I added the button, but I don't think it does anything... yet.
