### ISSUE TITLE
Shit's blurry, yo

### ISSUE THREAD

**Issue by jaqque** [jaqque/midjourney-split#4]
**Describe the bug**
shit's blurry

**To Reproduce**
1. Go to 'submission'
2. Hit return
3. Wait

**Expected behavior**
A clear picture

**Screenshots**
HA! I have better than screenshots! I have _printouts_

### Nothing of use follows

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
Submitted via Discord, translated by this submitter
https://discord.com/channels/753750469016551467/753750469553291291/1142484899840929863

I also lied when I said nothing of use follows. Or did I? 🤔

**Comment by jaqque** [comment]
.zip has been supplied with filter outputs; waiting on user acceptance testing

**Comment by NimbleJinx** [comment]
You really need to tag me if you expect higher response times. :) @jaqque
